services:
  codedefenders_llm_logs:
    image: postgres:latest
    container_name: codedefenders_llm_logs
    environment:
      POSTGRES_USER: {POSTGRES_USER}
      POSTGRES_PASSWORD: {POSTGRES_PASSWORD}
      POSTGRES_DB: logs
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
